name: 'Required Approval'

description: 'Verifies that this pull request has been approved by of required individuals'

branding:
  icon: 
  color: green

inputs:
  token:
    description: "GitHub token used for authentication"
    required: true
  required-approvers-list:
    description: 'The list of specific users that can approve the request, comma separated. '
    required: false
  min-required:
    description: 'The minimum number of approvals, e.g. 2'
    required: true
  mock-approvers:
    description: 'Used only for testing'
    required: false
  mock-pr-number:
    description: 'Used only for testing'
    required: false

outputs:
  specific-approvals:
    description: "The list of users that approved"
    value: ${{ steps.approval-check.outputs.approvers }}

runs:
  using: node16
  main: dist/index.js
