name: 'Approved By Maintainers'

description: 'Verifies that this pull request has been approved by maintainers'

inputs:
  token:
    description: "GitHub token used for authentication"
    required: true
  maintainers-file:
    description: 'The file where the maintainers are listed, defaults to MAINTAINERS.md'
    required: false
  min-required:
    description: 'The minimum number of maintainers required to approve, e.g. 2'
    required: true
  mock-approvers:
    description: 'Used only for testing'
    required: false

outputs:
  maintainer-approvals:
    description: "The list of maintainers that approved"
    value: ${{ steps.approval-check.outputs.maintainer-approvals }}

runs:
  using: "composite"
  steps:
    - run: |
        if [[ ! -e ${{ inputs.maintainers-file }} ]]; then
            echo "::error::Error: ${{ inputs.maintainers-file }} does not exist."
            exit 1
        fi
      shell: bash

    - run: |
        echo "maintainers=$(awk '/## Current Maintainers/ {flag=1; next} flag && /^\|/ {print $3} !/^\|/ && flag {exit}' ${{ inputs.maintainers-file }} | grep -oP '\[\K([^\]]+)')" >> $GITHUB_ENV
      shell: bash

    - run: |
        reviewers=$(curl -s -H "Authorization: token ${{ inputs.token }}" \
        "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/${{ github.event.pull_request.number }}/reviews")

        approvers=$(echo "$reviewers" | jq -r '.[] | select(.state == "APPROVED") | .user.login')
        echo "approvers=$approvers" >> $GITHUB_ENV
      shell: bash
      if: ${{ !inputs.mock-approvers }}
    
    - run: echo "approvers=${{ inputs.mock-approvers }}" >> $GITHUB_ENV
      shell: bash
      if: ${{ inputs.mock-approvers }}

    - run: |
        approvals_count=0
        maintainer_approvals=""
        for user in $approvers; do
          if [[ $MAINTAINERS =~ $user ]]; then
            echo "Approval by maintainer: $user"
            maintainer_approvals="$maintainer_approvals $user"
            ((approvals_count++))
          fi
        done
        echo "maintainer-approvals=$maintainer_approvals" >> $GITHUB_OUTPUT

        if [[ $approvals_count -eq 0 ]]; then
          echo "No approvals by listed maintainers."
          exit 1
        elif [[ $approvals_count -lt ${{ inputs.min-required }} ]]; then
          echo "::error::Not enough approvals by listed maintainers. Only $approvals_count out of required ${{ inputs.min-required }}."
          exit 1
        else
          echo "Received $approvals_count out of required ${{ inputs.min-required }} approvals by listed maintainers."
        fi
      shell: bash
      id: approval-check